server:
  port: 8761

spring:
  application:
    name: service-discovery
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

eureka:
  client:
    # Eureka 자체 서버는 등록 X
    register-with-eureka: false
    fetch-registry: false

