server:
  port: 0 # random port

spring:
  application:
    name: user-service

eureka:
  # instance_id 부여 (scale-out 시 별도 설정 필요 X)
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  # Eureka Server 등록
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
