version: 0.0 # CodeDeploy 버전 (프로젝트 버전이 아니면 0.0 이외는 오류 발생)
os: linux
files:
  - source: / # CodeDeploy에서 전달한 파일 중 destination으로 보낼 대상 지정 (/는 전체 파일)
    destination: /home/ec2-user/app2/step3/zip/ # source 파일을 받을 경로
    overwrite: yes # 덮어쓰기 여부

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있지 않은 스프링 부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh #엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user