token:
  expiration_time: 86400000
  secret: '{cipher}AQAPMX0IWdygwcnmo7Vhj+Nl3WJiQBwotdR1S9qXoG4bhpmSAwkBCll37lAKdH4HawbCKTPQ3yxoKu0i9LrnDidKrPcRA9UAzXGvBCHb1ES2KguQVdkFJVW0WVY0LXsV3iPFhg2Y77ITbaVuyZKJAmlJdH/srM4ibx4Z1Ymh15B1jy6977OpDgQzSL9V4qI3lxvejO08BIadkmO5/KoN8GzOSTbv3gQ4LZZWP6XuyaHxPi7X9I08j/v6PpSuGCCgkh6booEiT1FpUtRjz6oV/9YH8SAebqRPIYE4fLQYEt/HtIOE6hulowY+xK9jRjS0gXnd44ekL7PNG2mQ6+wHrKVlDgkrxs+QMNY+fF1bxGogOzJTuK6KYXsZ1AzwNKSSQpzlR2+mErkO08JO18zHco/hpUNxd3uYo6Rmbdj1QhCkx14SR37XO7gUIAVjV1c6RTntHMnanxt12blEqAzE8RJZkybKYLUYSTLL0FDMJ+Q1ba9IumRKzMpVcwO/IDArinXxHuicQEyE+Czf3xOoTe7U'

gateway:
  ip: 127.0.0.1
