token:
  expiration_time: 86400000
  secret: '{cipher}AQBVVL79WhVgaF3nKhqCS2xmZ9vj/SvPaQkU9SE/HlnuDB1rdMmvHqELGMzag9xqOk5PJgoe0XVFXGUXYjO0gtLNw6zDwXewmfAErgizzj7wN+UXoatQ71PRrXTVs079qno8qx+DXYr9gQ4A4EKiEeaP9/QWgWKlupKz5feYiXVnJwjSFMO4Ff8GDCOmfvnbkoLFRVnvsnGJqRFg6ZXidXlOVw9TUaEV/zjm3xyoncMilmE15WPtu4e9tljwQSE4hugAQaD9db34y4LoUNgpakjPSo0wzBj6FeD/4tNEQ1zRwqclJ54bFPd9SYFFUYTzMCmEewnx1oRbfrVLGT4DgRrfIN+JjYLFk1Yyt6Bnixtq6OMhO61UO0en04C6oNRgW8UD/QGTOtMuLTHM/MGmEWALyVYm0UqGkkyhefh3oaBIiJ9sAOpQiBU58hM61iMn51mJmJ7QhdGhMtXLji9gzKp7AyraIqH/bUhz8nLpBC/cNp5MOcUY24kiddI6S/AQDVWMPV8eKiG4gQfTY/Q4B3E8'

gateway:
  ip: 172.18.0.6
