services:
  ### Message Queue (RabbitMQ, Zookeeper, Kafka, Kafka Connect) ###
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"   # AMQP 포트
      - "15671:15671"
      - "15672:15672" # 관리 UI 포트
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ecommerce

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper     # 컨테이너 내부에서 zookeeper를 'zookeeper' 호스트명으로 접근 가능
    container_name: zookeeper
    ports:
      - "2181:2181"         # 호스트의 2181 포트를 컨테이너의 2181 포트에 매핑 (Zookeeper 클라이언트 포트)
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181    # Zookeeper 클라이언트 연결 포트 설정
      ZOOKEEPER_TICK_TIME: 2000      # Zookeeper tickTime 설정 (Zookeeper 내부 유지 보수용 heartbeat 단위)
    networks:
      ecommerce:
        ipv4_address: 172.18.0.100

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker         # Kafka 컨테이너 내부에서 'broker' 라는 호스트명으로 접근 가능
    container_name: broker
    ports:
      - "29092:29092"        # 내부(컨테이너간) 통신용 Kafka 포트(ADVERTISED_LISTENERS에 선언)
      - "9092:9092"          # 외부(호스트)에서 접속 시 사용할 포트
      - "9101:9101"          # JMX 모니터링용 포트
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'  # Kafka가 Zookeeper와 통신하기 위한 주소(같은 네트워크 상에서 zookeeper로 접근)
      # Kafka 서버의 실제 호스트 정보 (Kafka Container의 IP Addr 할당)
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.101
      # PLAINTEXT와 PLAINTEXT_HOST 두 가지 리스너 이름을 사용하고, 둘 다 PLAINTEXT 프로토콜로 매핑
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      # 컨테이너 내부(네트워크 내)에서 Kafka 브로커를 접근할 때: PLAINTEXT://broker:29092
      # 호스트 머신에서 접근할 때: PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # 오프셋 토픽 복제 팩터 (단일 브로커이므로 1)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # JMX 호스트명 및 포트 설정(모니터링용)
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # Topic 초기화
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper            # broker는 zookeeper 기동 후 시작
    networks:
      ecommerce:
        ipv4_address: 172.18.0.101

  connect:
    image: confluentinc/cp-kafka-connect:latest
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"    # Kafka Connect REST API 접근 포트 (호스트에서 localhost:8083으로 접근 가능)
    environment:
      # broker:29092 → 브로커 컨테이너 내부 이름 및 포트 사용 (내부 네트워크용)
      CONNECT_BOOTSTRAP_SERVERS: broker:29092
      # Connect REST API 포트 설정
      CONNECT_REST_PORT: 8083
      # Connect 클러스터용 그룹 아이디
      CONNECT_GROUP_ID: "quickstart-avro"
      # Connect 내부 관리용 토픽 이름들(구성정보, 오프셋, 상태 저장용)
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      # 내부 토픽들의 복제 팩터(단일 브로커 환경이므로 1로 설정)
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      # 메시지와 내부 데이터 변환기(Converter) 설정 (JSON 기반으로 사용)
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      # REST API를 외부에 광고할 때 사용할 호스트명 (호스트에서 localhost:8083로 접속)
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      # 로그 레벨 WARN으로 설정 (불필요한 로그 감소)
      CONNECT_LOG4J_ROOT_LOGLEVEL: WARN
      # 커넥트 플러그인(커넥터) 검색 경로 설정
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
    volumes:
      - ./plugins/kafka-connect:/etc/kafka-connect/jars
      - ./plugins/kafka-connect:/etc/kafka-connect/jars
    depends_on:
      - broker    # kafka 브로커가 먼저 올라온 후 connect 실행
    links:
      - zookeeper
      - broker
    networks:
      - ecommerce

  ### RDB (Postgresql) ###
  postgres:
    image: postgres:14.5
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"  # 호스트에서 localhost:5432로 PostgreSQL 접근 가능
    environment:
      # postgres 데이터베이스 초기 환경 설정(DB명, 유저명, 비밀번호)
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test1357
    volumes:
      # 호스트 볼륨(db-data)을 컨테이너 내부의 PGDATA 디렉토리에 매핑, 데이터 영속화
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - ecommerce

  ### 분산 추적 (Zipkin) ###
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    hostname: zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - ecommerce

  ### Monitoring (Prometheus, Grafana)###
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - ecommerce

  grafana:
    image: grafana/grafana:latest
    hostname: grafan
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - ecommerce

  ### Microservices ###
  configuration-server:
    image: jsj1275/configuration-server:0.0.1-SNAPSHOT
    hostname: configuration-server
    container_name: configuration-server
    ports:
      - "8888:8888"
    environment:
      - "spring.rabbitmq.host=rabbitmq"
      - "spring.profiles.active=default"
    networks:
      - ecommerce

  service-discovery:
    image: jsj1275/service-discovery:0.0.1-SNAPSHOT
    hostname: service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - "spring.cloud.config.uri=http://configuration-server:8888"
    depends_on:
      - configuration-server
    networks:
      - ecommerce

  api-gateway:
    image: jsj1275/api-gateway:0.0.1-SNAPSHOT
    hostname: api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - "spring.cloud.config.uri=http://configuration-server:8888"
      - "spring.rabbitmq.host=rabbitmq"
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka"
    depends_on:
      - configuration-server
    networks:
      - ecommerce

  user-service:
    image: jsj1275/user-service:0.0.1-SNAPSHOT
    hostname: user-service
    container_name: user-service
    environment:
      - "spring.cloud.config.uri=http://configuration-server:8888"
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka"
      - "spring.rabbitmq.host=rabbitmq"
      - "management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans"
      - "logging.file.name=/api-logs/users-ws.log"
      - "logging.file.path=/api-logs"
    depends_on:
      - configuration-server
      - service-discovery
      - rabbitmq
      - zipkin
    networks:
      - ecommerce

  order-service:
    image: jsj1275/order-service:0.0.1-SNAPSHOT
    hostname: order-service
    container_name: order-service
    environment:
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka"
      - "management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans"
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/test"
      - "kafka-url=172.18.0.101:29092"
      - "logging.file.name=/api-logs/orders-ws.log"
      - "logging.file.path=/api-logs"
    depends_on:
      - service-discovery
      - zipkin
      - postgres
      - broker
    networks:
      - ecommerce

  catalog-service:
    image: jsj1275/catalog-service:0.0.1-SNAPSHOT
    hostname: catalog-service
    container_name: catalog-service
    environment:
      - "eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka"
      - "kafka-url=172.18.0.101:29092"
      - "logging.file.name=/api-logs/catalog-ws.log"
      - "logging.file.path=/api-logs"
    depends_on:
      - service-discovery
      - broker
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  db-data:
  prometheus_data:
  grafana_data:
